apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfig
data:
  db_host: localhost
  db_port: "3306"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appconfig
data:
  app.prop: |
    title=Application
    version=1.0.0
---
apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
data:
  db_user: cm9vdA==
  db_pass: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: cmdemo
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: dbconfig
              key: db_host
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: dbconfig
              key: db_port
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: db_user
      volumeMounts:
      - name: dbconfig
        mountPath: "/config/db"
        readOnly: true
      - name: appconfig
        mountPath: "/config/app"
        readOnly: true
  volumes:
    - name: dbconfig
      secret:
        secretName: dbsecret
    - name: appconfig
      configMap:
        name: appconfig
        items:
        - key: app.prop
          path: app.properties
