apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stable
  labels:
    version: "1.16"
    app: nginx
    tier: frontend
spec:
  replicas: 4                  # Number of replicas
  strategy:
    type: Recreate
  selector:                    # Pod selector. Match all pods with specified labels
    matchLabels:
      version: "1.16"
      app: nginx
      tier: frontend
  template:                    # Pod template used to create new pods
    metadata:
      labels:
        version: "1.16"
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          httpGet:
            path: /
            port: 80
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash","-c","sleep 30"]
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
